import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1 className='bg-black text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum deserunt impedit ut placeat, eos, nihil ad quasi delectus reprehenderit ullam mollitia laborum ipsa totam et recusandae quibusdam. Culpa, animi autem.</h1>
      </main>
    </>
  )
}
